import json
from typing import Any, Dict

from app.agents.base import BaseAgent
from app.config import settings
from app.llm import explain_with_openrouter, get_openrouter_client
from app.models.common import AgentOutput
from app.models.llm import MarketAnalysis
from app.utils.logger import get_logger

logger = get_logger("agent.market")


class MarketAgent(BaseAgent):
    """Market Agent: provides location-aware market guidance."""

    MARKET_DATA = {
        "maharashtra": {
            "rice": {"price": 1800, "trend": "stable", "volatility": "low"},
            "wheat": {"price": 2200, "trend": "up", "volatility": "medium"},
            "tomato": {"price": 2500, "trend": "stable", "volatility": "high"},
        },
        "punjab": {
            "rice": {"price": 1900, "trend": "down", "volatility": "medium"},
            "wheat": {"price": 2400, "trend": "up", "volatility": "low"},
            "tomato": {"price": 2800, "trend": "up", "volatility": "high"},
        },
        "default": {
            "rice": {"price": 1800, "trend": "stable", "volatility": "medium"},
            "wheat": {"price": 2200, "trend": "stable", "volatility": "medium"},
            "tomato": {"price": 2500, "trend": "stable", "volatility": "high"},
        },
    }

    def __init__(self):
        super().__init__(
            name="MarketAgent",
            description="Provides market prices and trends",
        )
        self.client = get_openrouter_client()

    async def execute(self, input_data: Dict[str, Any]) -> AgentOutput:
        crop_type = (input_data.get("crop_type") or "rice").lower()
        location = (input_data.get("location") or "default").lower()

        if self.client.is_configured:
            try:
                analysis = await explain_with_openrouter(
                    system_prompt=self._system_prompt(),
                    user_prompt=self._user_prompt(crop_type, location),
                    schema_model=MarketAnalysis,
                    temperature=0.1,
                    max_tokens=900,
                    reasoning_effort="medium",
                    model=settings.openrouter_model,
                )
                # Ensure price is not None, use fallback if needed
                price = analysis.current_price_per_quintal
                if price is None:
                    region_data = self.MARKET_DATA.get(location, self.MARKET_DATA["default"])
                    market_info = region_data.get(crop_type, region_data.get("rice"))
                    price = market_info.get("price", 1800)
                    logger.warning("market_openrouter_null_price", fallback_price=price)
                
                return AgentOutput(
                    agent_name=self.name,
                    status="success",
                    result={
                        "crop_type": analysis.crop_type or crop_type,
                        "location": analysis.location or location,
                        "current_price_per_quintal": price,
                        "market_trend": analysis.market_trend or "stable",
                        "price_volatility": analysis.price_volatility or "medium",
                        "recommendation": analysis.recommendation or "Market analysis complete",
                        "confidence": analysis.confidence or 0.7,
                        "uncertainties": analysis.uncertainties or [],
                        "analysis_source": "openrouter",
                    },
                    confidence=analysis.confidence or 0.7,
                    reasoning=analysis.recommendation or "Market recommendation generated by OpenRouter.",
                    latency_ms=0,
                )
            except Exception as exc:
                logger.warning("market_openrouter_failed", error=str(exc))

        region_data = self.MARKET_DATA.get(location, self.MARKET_DATA["default"])
        market_info = region_data.get(crop_type, region_data.get("rice"))
        recommendation = self._get_recommendation(market_info.get("trend"), market_info.get("price"))

        return AgentOutput(
            agent_name=self.name,
            status="success",
            result={
                "crop_type": crop_type,
                "location": location,
                "current_price_per_quintal": market_info.get("price"),
                "market_trend": market_info.get("trend"),
                "price_volatility": market_info.get("volatility"),
                "recommendation": recommendation,
                "confidence": 0.85,
                "analysis_source": "fallback",
            },
            confidence=0.85,
            reasoning="Market data sourced from local regional defaults.",
            latency_ms=0,
        )

    def _system_prompt(self) -> str:
        return (
            "You are a market advisory assistant for crops. Use the crop, location, and "
            "current disease context to give practical guidance. Return structured JSON only."
        )

    def _user_prompt(self, crop_type: str, location: str) -> str:
        return json.dumps(
            {
                "crop_type": crop_type,
                "location": location,
                "market_defaults": self.MARKET_DATA.get(location, self.MARKET_DATA["default"]),
                "instructions": [
                    "Estimate a reasonable price per quintal if explicit live data is unavailable.",
                    "Provide a trend, volatility level, recommendation, and confidence.",
                    "Explain market advice in a concise farmer-friendly way.",
                ],
            },
            ensure_ascii=False,
            indent=2,
        )

    def _get_recommendation(self, trend: str, price: float) -> str:
        if trend == "up":
            return "Market prices are rising. Prioritize disease prevention and avoid rushed sales."
        if trend == "down":
            return "Market prices are soft. Focus on cost-effective treatments and harvest timing."
        return "Market is relatively stable. Standard disease control and planning are appropriate."
