"""Initial schema

Revision ID: 5d05b0dcd086
Revises: 
Create Date: 2026-07-07 14:23:03.248703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d05b0dcd086'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_created_at'), 'farmers', ['created_at'], unique=False)
    op.create_index(op.f('ix_farmers_email'), 'farmers', ['email'], unique=True)
    op.create_index(op.f('ix_farmers_region'), 'farmers', ['region'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('primary_disease', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_created_at'), 'diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_crop_type'), 'diagnoses', ['crop_type'], unique=False)
    op.create_index(op.f('ix_diagnoses_farmer_id'), 'diagnoses', ['farmer_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_name'), 'agent_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_logs_diagnosis_id'), 'agent_logs', ['diagnosis_id'], unique=False)
    op.create_table('diagnosis_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('observed_symptoms', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('contradicting_evidence', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_evidence_diagnosis_id'), 'diagnosis_evidence', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_evidence_disease_name'), 'diagnosis_evidence', ['disease_name'], unique=False)
    op.create_table('diagnosis_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_observations_diagnosis_id'), 'diagnosis_observations', ['diagnosis_id'], unique=False)
    op.create_table('treatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('expected_yield_recovery', sa.Float(), nullable=True),
    sa.Column('estimated_days_to_recovery', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatments_diagnosis_id'), 'treatments', ['diagnosis_id'], unique=False)
    op.create_table('vision_observation_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('original_hash', sa.String(length=64), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=True),
    sa.Column('gemini_model', sa.String(length=100), nullable=False),
    sa.Column('image_bytes', sa.Integer(), nullable=True),
    sa.Column('preprocessed_bytes', sa.Integer(), nullable=True),
    sa.Column('image_quality_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('follow_up_questions', sa.JSON(), nullable=False),
    sa.Column('quality_notes', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('needs_follow_up', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_vision_observation_cache_crop_type'), 'vision_observation_cache', ['crop_type'], unique=False)
    op.create_index(op.f('ix_vision_observation_cache_created_at'), 'vision_observation_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_vision_observation_cache_image_hash'), 'vision_observation_cache', ['image_hash'], unique=True)
    op.create_index(op.f('ix_vision_observation_cache_original_hash'), 'vision_observation_cache', ['original_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatments_diagnosis_id'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index(op.f('ix_vision_observation_cache_original_hash'), table_name='vision_observation_cache')
    op.drop_index(op.f('ix_vision_observation_cache_image_hash'), table_name='vision_observation_cache')
    op.drop_index(op.f('ix_vision_observation_cache_created_at'), table_name='vision_observation_cache')
    op.drop_index(op.f('ix_vision_observation_cache_crop_type'), table_name='vision_observation_cache')
    op.drop_table('vision_observation_cache')
    op.drop_index(op.f('ix_diagnosis_observations_diagnosis_id'), table_name='diagnosis_observations')
    op.drop_table('diagnosis_observations')
    op.drop_index(op.f('ix_diagnosis_evidence_disease_name'), table_name='diagnosis_evidence')
    op.drop_index(op.f('ix_diagnosis_evidence_diagnosis_id'), table_name='diagnosis_evidence')
    op.drop_table('diagnosis_evidence')
    op.drop_index(op.f('ix_agent_logs_diagnosis_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_created_at'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_name'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_diagnoses_farmer_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_crop_type'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_created_at'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_farmers_region'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_email'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_created_at'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
